name: Docker Compose Action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"
          up-flags: "--build"

      - name: Wait for services to be ready
        run: sleep 10

      - name: Execute tests in the running services
        run: docker compose exec -T playwright npm run test
